(function(g){var window=this;var u4=function(a){var b={format:a.A,languageCode:a.o,languageName:a.D,displayName:g.bI(a),kind:a.B,name:a.C,id:a.Ba,is_servable:a.M,is_translateable:a.G,vss_id:a.F};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},v4=function(a){return a.g?a.g.languageCode:a.o},pxa=function(a,b){var c=new g.aI;
c.o=a.o;c.D=a.D;c.C=a.C;c.B=a.B;c.G=a.G;c.F=a.F;c.I=a.I;c.g=b;return c},qxa=function(a){a=g.nd(window.document,"track",void 0,a.g);
for(var b=0;b<a.length;b++)g.Hd(a[b])},rxa=function(a){for(var b in a)delete a[b]},sxa=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},w4=function(a){if(!txa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(uxa,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},x4=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.VP.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.C=f;this.o=k},y4=function(a,b,c,d,e){g.VP.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},A4=function(a){a=void 0===a?{}:a;
var b="_"+z4++;return new y4(0,0x8000000000000,0,b,a)},B4=function(a,b,c,d,e,f){var k={};
g.Ga(k,b);g.Ga(k,a.params);g.Ga(k,c);var l={};g.Ga(l,b.kb);a.params.kb&&g.Ga(l,a.params.kb);g.Ga(l,c.kb);k.kb=l;g.Y.call(this,{H:"div",N:"caption-window",V:{id:"caption-window-"+a.id,dir:1==k.ck?"rtl":"ltr",tabindex:0,"aria-live":"assertive",lang:k.lang},K:[{H:"span",N:"captions-text"}]});this.A=[];this.J=!1;this.F=a;this.D=[];this.G=[];this.xa=e;this.pa=f;this.C=null;this.R=.96*e;this.ea=.96*f;this.o=k;this.na=c;this.B=this.ra["captions-text"];this.ga=null!=this.B.style["box-decoration-break"]||
null!=this.B.style["-webkit-box-decoration-break"];this.L=d/360*16;this.type=0;this.aa=this.L*vxa(l);a=new g.aG(this.element,!0);g.M(this,a);a.subscribe("dragstart",this.cL,this);a.subscribe("dragmove",this.bL,this);a.subscribe("dragend",this.aL,this);this.da=this.ca=0;a="";this.o.pk&&(a=w4(this.o.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.pk+")");b={"background-color":a,display:!1===this.o.isVisible?"none":"","text-align":wxa[this.o.textAlign]};this.ga&&(b["border-radius"]=a?this.aa/
8+"px":"");g.oh(this.element,b);switch(this.o.Vg){case 0:case 1:case 2:g.R(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.R(this.element,"ytp-caption-window-bottom")}},vxa=function(a){var b=1+.25*(a.dj||0);
if(0==a.offset||2==a.offset)b*=.8;return b},C4=function(a,b){var c={},d=b.background?b.background:a.o.kb.background;
if(null!=b.Ve||b.background){var e=null!=b.Ve?b.Ve:a.o.kb.Ve;d=w4(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.ga&&(c["box-decoration-break"]="clone",c["border-radius"]=a.aa/8+"px")}if(null!=b.dj||null!=b.offset)c["font-size"]=a.L*vxa(b)+"px";d=1;e=b.color||a.o.kb.color;if(b.color||null!=b.Gh)e=w4(e),d=null==b.Gh?a.o.kb.Gh:b.Gh,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.Sh;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";
b.jw&&(k=e=b.jw);var l=a.L/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';
break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.UE()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e=
'"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.o.kb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Wr&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");b.qr&&(c.visibility="hidden");return c},xxa=function(a,b,c){a.J=a.J||!!c;
var d={};g.Ga(d,a.o.kb);g.Ga(d,c||b.o);g.Ga(d,a.na.kb);c=a.D[0];if(c&&d.background==c.background&&d.Ve==c.Ve&&!!d.qr==!!c.qr&&d.Sh==c.Sh){var e;for(e=0;e<a.D.length;e++)if(sxa(d,a.D[e])){var f=a.G[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.Bd("SPAN");g.oh(f,C4(a,e));a.G[0].appendChild(f);e=1}a.G.length=e;a.D.length=e}else a.G.length=0,a.D.length=0,f=g.Bd("SPAN"),g.oh(f,C4(a,d)),a.B.appendChild(f);a.C&&a.C.parentNode!=f&&(g.Hd(a.C),f.appendChild(a.C));c=(k=g.u(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.A.length||!b.C){if(0<e||0!=a.A.length){var m=g.Bd("BR");f.appendChild(m)}f.appendChild(g.Cd("\u00a0"));a.C=g.Cd("\u00a0");f.appendChild(a.C)}l&&(m=a.C,m.parentNode&&m.parentNode.insertBefore(k?g.Cd(l):l,m))}a.D.push(d);a.G.push(f);a.A.push(b)},yxa=function(){},E4=function(a){this.F=a;
this.B=this.o=this.mode=this.A=0;this.C=new D4(this);this.D=new D4(this);this.g=[];this.clear()},Axa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Jm:a,
Km:b,result:0};a=zxa[a];b=zxa[b];if(a&128){if(!(b&128)&&0!=c.g&&c.o==b)return{Jm:a,Km:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Jm:a,Km:b,result:2};return{Jm:a,Km:b,result:3}},Cxa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.B&&a.reset(),a.C.g.clear(),a.D.g.clear()):(a.B=0,Bxa(a.C,b,c,d))},Dxa=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.o=d.time;0==d.type?Cxa(a,d.dw,d.ew,b):1==d.type&&a.A&496&&Bxa(a.D,d.dw,d.ew,b)}a.g.length=0},F4=function(){this.g=0},G4=function(){this.o=this.A=this.g=0},H4=function(){this.timestamp=this.qe=0;
this.g=!1},I4=function(a){this.A=[];
for(var b=0;15>=b;b++){this.A[b]=[];for(var c=0;32>=c;c++)this.A[b][c]=new H4}this.g=this.o=this.Dc=0;this.style=new F4;this.C=a;this.B=0},J4=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.C.o+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.A[m][q];
if(0!=r.qe){0==c&&(c=m,d=q);n=String.fromCharCode(r.qe);var v=r.timestamp;v<e&&(e=v);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.qe||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.o+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.A[k][m],r=q.qe,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),v=q.timestamp,v<=e&&(e=v),l+=n,q.reset()),32==m||0==r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},Ixa=function(a,b){switch(a){case 0:return Exa[(b&127)-32];
case 1:return Fxa[b&15];case 2:return Gxa[b&31];case 3:return Hxa[b&31]}return 0},K4=function(a){return a.A[a.Dc][a.o]},L4=function(a,b,c){2<=b&&1<a.o&&(--a.o,K4(a).qe=0);
var d=K4(a);d.timestamp=a.C.o+0;d.qe=Ixa(b,c);32>a.o&&a.o++},Jxa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.A[b+e][f].cn(a.A[c+e][f])},M4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},N4=function(a){a.Dc=0<a.g?a.g:1;
a.o=1;M4(a,0,15)},O4=function(a){this.B=a;
this.C=0;this.style=new F4;this.D=new I4(a);this.F=new I4(a);this.G=new I4(a);this.o=this.D;this.A=this.F;this.g=this.o},P4=function(a,b,c){var d=a.o,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:J4(d,c),N4(a.o),N4(a.A),d.Dc=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.B.mode=1<<d.B;e?d.o=1:d.g!=b&&(d.g>b?(J4(d,c),M4(d,d.Dc-d.g,b)):d.Dc<b&&(b=d.g),d.g=b)},Kxa=function(a){a.style.set(1);
a.g=a.A;a.g.g=0;a.g.style=a.style;a.B.mode=1<<a.g.B},Lxa=function(a){a.style.set(4);
a.g=a.G;a.g.style=a.style;a.B.mode=1<<a.g.B},D4=function(a){this.o=a;
this.g=new G4;this.C=0;this.A=new O4(a);this.D=new O4(a);this.B=this.A},Bxa=function(a,b,c,d){a.g.update();
b=Axa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Jm;c=b.Km;if(32<=e||!e)a.o.mode&a.o.A&&(b=e,b&128&&(b=127),c&128&&(c=127),e=a.B.g,b&96&&L4(e,0,b),c&96&&L4(e,0,c),!a.o.F&&0!=b&&0!=c&&3==e.style.g&&J4(e,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.A=e,b.o=c,b.g=2,b=e&8?a.D:a.A,a.B=b,a.o.mode=1<<(a.C<<2)+(b.C<<1)+(4==b.style.g?1:0),(a.o.mode|1<<(a.C<<2)+(b.C<<1)+(4!=b.style.g?1:0))&a.o.A))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&
14)>>1):0;c=b.g;switch(b.style.get()){case 4:d=c.Dc;break;case 3:if(d!=c.Dc){if(d<c.g&&(d=c.g,d==c.Dc))break;var f=1+c.Dc-c.g,k=1+d-c.g;Jxa(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));M4(c,b,e)}}c.Dc=d;c.o=a+1}else switch(e&7){case 1:switch(c&112){case 32:L4(b.g,0,32);break a;case 48:57==c?(b=b.g,K4(b).qe=0,32>b.o&&b.o++):L4(b.g,1,c&15)}break;case 2:c&32&&L4(b.g,2,c&31);break;case 3:c&32&&L4(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Kxa(b);break;
case 33:b=b.g;1<b.o&&(--b.o,K4(b).qe=0);break;case 36:b=b.g;d=K4(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.A[a][c]==d){for(;32>=c;c++)b.A[a][c].reset();break}break;case 37:P4(b,2,d);break;case 38:P4(b,3,d);break;case 39:P4(b,4,d);break;case 40:L4(b.g,0,32);break;case 41:b.style.set(2);b.g=b.o;b.g.g=0;b.g.style=b.style;b.B.mode=1<<b.g.B;break;case 42:d=b.G;d.g=15;d.style.set(4);N4(d);Lxa(b);break;case 43:Lxa(b);break;case 44:a=b.o;switch(b.style.get()){case 1:case 2:case 3:J4(a,d)}M4(a,0,15);break;
case 45:b:{a=b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.Dc){++a.Dc;a.o=1;break b}case 3:}2>a.g&&(a.g=2,a.Dc<a.g&&(a.Dc=a.g));b=a.Dc-a.g+1;J4(a,d);Jxa(a,b,b+1,a.g-1);M4(a,a.Dc,1)}break;case 46:M4(b.A,0,15);break;case 47:J4(b.o,d);d=b.A;a=b.B.o+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.A[c][e].timestamp=a;d=b.A;b.A=b.o;b.o=d;Kxa(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.o+=c&3)&&(b.o=32)}}},Q4=function(){},R4=function(a){this.A=a;
this.o=null},Nxa=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.Ur("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");Mxa(d,e,k,b,f,a.firstChild,{},c)},Mxa=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.Wr=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");S4.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new x4(a,b,c,d,n.nodeValue,e||0<m,g.Yb(k)?void 0:k));else{var q={};g.Ga(q,k);Mxa(a,b,c,d,e||0<m,n,q,l)}}},T4=function(){this.A={};
this.o=null},U4=function(a){this.o={};
this.C={};this.D={};this.A="_"+z4++;this.B=a},V4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},W4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},X4=function(a,b){var c=V4(a,b);
if(void 0!=c)return c},Y4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return S4.test(c),c},Oxa=function(a,b){var c={},d=b.getAttribute("ws");
g.Ga(c,d?a.D[d]:a.B);d=X4(b,"mh");null!=d&&(c.rs=d);d=X4(b,"ju");null!=d&&(c.textAlign=d);d=X4(b,"pd");null!=d&&(c.ck=d);d=Y4(b,"wfc");null!=d&&(c.windowColor=d);d=V4(b,"wfo");void 0!=d&&(c.pk=d/255);return c},Pxa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ga(c,a.C[d]);d=X4(b,"ap");null!=d&&(c.Vg=d);d=V4(b,"cc");null!=d&&(c.XG=d);d=V4(b,"ah");null!=d&&(c.ni=d);d=V4(b,"rc");null!=d&&(c.So=d);d=V4(b,"av");null!=d&&(c.Mi=d);return c},Qxa=function(a,b,c){var d={};
g.Ga(d,Pxa(a,b));g.Ga(d,Oxa(a,b));c?sxa(d,a.B)?(c=a.A,d=a.B):c="_"+z4++:c=b.getAttribute("id")||"0";a=V4(b,"t");b=V4(b,"d")||0x8000000000000;return new y4(a,b,0,c,d)},Z4=function(a,b,c){this.F=c;
this.version=this.C=this.D=this.g=0;this.o=new window.DataView(a);this.A=[]},$4=function(a){var b=a.g;
a.g+=1;return a.o.getUint8(b)},Rxa=function(a){var b=a.g;
a.g+=4;return a.o.getUint32(b)},a5=function(a,b){this.A=a;
this.track="CC3"==b.D?4:0;this.o=new E4(!1);this.o.A=1<<this.track},Sxa=function(a){if(!(a.g<a.o.byteLength))return!1;
var b=Rxa(a);b.toString(16);if(1380139777!=b)return!1;a.version=$4(a);if(1<a.version)return!1;$4(a);$4(a);$4(a);return!0},Txa=function(){this.o=[];
this.g=[]},b5=function(a,b){return b?a.g.concat(a.o):a.g},c5=function(a,b){switch(b.B){case "asr":var c=a.o;
g.fb(c,(0,g.z)(b.J,b))||c.push(b);break;default:c=a.g,g.fb(c,(0,g.z)(b.J,b))||c.push(b)}},d5=function(){this.o=null},Uxa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Wr=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new x4(b,c,d,e.id,q.nodeValue,f||0<n,g.Yb(l)?void 0:l),m.push(q),e!=a.o&&e.o.push(q);else{var r={};g.Ga(r,l);Uxa(a,b,c,d,e,!0,q,r,m)}}},e5=function(a){var b=0;
a=g.ma(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+c.value;return 1E3*b},f5=function(a){g.L.call(this);
this.vy=!!a;this.o=new Txa;this.F=[];this.g=null},Wxa=function(a){var b={};
if(a=v4(a))b.lang=a,Vxa.test(a)&&(b.ck=1);return b},Xxa=function(a,b,c,d,e){d=d||0;
e=e||0;if(g.u(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new d5),a.g.g(b,d);b=g.Ur(b);if(!b||!b.firstChild)return[];a.g||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new U4(Wxa(c)):a.g=new T4:a.g=new R4(Wxa(c)));return a.g.g(b,d)}try{if(g.u(b))var f=!1;else{var k=new Z4(b,0,0);f=Sxa(k)}if(f)return a.g||(a.g=new a5(e,c)),a.g.g(b,d)}catch(l){g.rE(l)}return[]},g5=function(a){f5.call(this,a.Qm);
this.B=void 0;this.A=null;this.F=a.captionTranslationLanguages},h5=function(){this.qb=[]},i5=function(a,b,c,d,e,f){g.L.call(this);
this.J=b;this.B=new h5;this.g=null;this.D=d;this.I=f;this.o=this.A=null;this.L=c;this.C=e||!1;this.F=new g.Xt(this.Jy,1E3,this);g.M(this,this.F);this.G=new g.WF(this);g.M(this,this.G);this.G.P(b,"seekto",this.wz);this.wz(b.getCurrentTime());this.Jy()},j5=function(a,b){f5.call(this);
this.B=a;this.C=b;this.A=null;this.D=!1},Yxa=function(a,b){if(b in a.B.g)return a.B.g[b];
if(g.wK(a.B))for(var c in a.B.g){var d=a.B.g[c];if(d.info.mimeType.includes("vtt"))return d}return null},k5=function(a,b,c,d,e,f){B4.call(this,a,b,c,d,e,f);
this.type=1},l5=function(a,b,c,d,e,f){B4.call(this,a,b,c,d,e,f);
g.R(this.element,"ytp-caption-window-rollup");this.type=2;this.I=this.M=0;this.O=window.NaN;this.la=null;this.X=new g.Xt(this.XQ,433,this);g.M(this,this.X)},m5=function(a){if(!a.M){var b=g.Bd("SPAN");
g.oh(b,C4(a,a.o.kb));a.B.appendChild(b);b.appendChild(g.Cd("M"));var c=b.offsetHeight,d=g.Bd("BR");b.appendChild(d);b.appendChild(g.Cd("M"));a.M=b.offsetHeight-c;a.B.removeChild(b)}return a.M},n5=function(a,b,c,d){f5.call(this,d);
c=c||g.CE(a).hl||"";c=c.split("_").join("-");this.C=g.EE(a,{hl:c});this.B=b;this.D={};this.A=null},q5=function(a){g.EV.call(this,a);
g.RD();this.B=g.X(a);this.A=a.fa();this.la=g.JU(a);this.L=a;var b=null,c=g.eD("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.TC(c));this.ca=b;this.D={kb:{}};this.I={kb:{}};this.M=[];this.O={};this.aa={};this.Y=!1;this.na="1"==this.A.Xb.cc_auto_caps||"1"==this.B.Xa.cc_auto_caps;this.G="3"==this.B.A&&!!a.app.C&&!!a.app.C.g.textTracks;c=b=this.o=this.C=this.F=this.J=this.X=this.ga=null;this.G||(b=new g.Ut(this.ZC,void 0,this),g.M(this,b),c=new g.Xt(this.LS,2E3,this),g.M(this,c));this.da=
b;this.ea=c;this.R=new g.WF(this);g.M(this,this.R);this.G||this.R.P(a,"resize",this.lu);this.R.P(a,"onPlaybackAudioChange",this.eO);this.R.P(a,"crn_captions",this.IK,this);this.R.P(a,"crx_captions",this.JK,this);o5(this,p5(this,"display-settings")||{})},Zxa=function(a){if(a.A.captionTracks.length)var b=a.g.xh().aw;
if("FORCED_ON"==b||1==a.B.Zg||1==a.A.Zg||"alwayson"==g.WN(a.A,"yt:cc"))return!0;if(2==a.B.Zg){var c=p5(a,"module-enabled");if(null!=c)return!!c}return"ON"==b||"on"==g.WN(a.A,"yt:cc")},$xa=function(a,b){if(a.C){var c=b5(a.C.o,b||a.na);
if(a.F&&a.F.g)return a.F.g;for(var d=[a.A.Yg,a.B.Yg,g.WN(a.A,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(v4(c[f])==d[e])return c[f];return a.F&&a.F.yq?a.F.yq:c[0]||a.F&&a.F.Hk}return null},aya=function(a,b){for(var c=a.L.app.C.g.textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},r5=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.Y=c);a.o=b;a.load(d)},bya=function(a,b){var c=g.nY(a.la,!0).height;
if(!c)return null;var d=a.la.Ua();switch(null!=b.params.rs?b.params.rs:b.params.uT?2:1<b.o.length?1:0){case 1:return new k5(b,a.D,a.I,c,d.width,d.height);case 2:return new l5(b,a.D,a.I,c,d.width,d.height);default:return new B4(b,a.D,a.I,c,d.width,d.height)}},o5=function(a,b,c){var d=s5.kb;
a.D={};g.Ga(a.D,s5);a.D.kb={};g.Ga(a.D.kb,d);a.I={kb:{}};var e=b.backgroundOverride?a.I:a.D,f=b.background||d.background;S4.test(f);e.kb.background=f;e=b.colorOverride?a.I:a.D;f=b.color||d.color;S4.test(f);e.kb.color=f;e=b.windowColorOverride?a.I:a.D;f=b.windowColor||s5.windowColor;S4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.I:a.D;f=b.backgroundOpacity;null==f&&(f=d.Ve);e.kb.Ve=f;e=b.fontSizeIncrementOverride?a.I:a.D;f=b.fontSizeIncrement;null==f&&(f=d.dj);e.kb.dj=f;e=b.textOpacityOverride?
a.I:a.D;f=b.textOpacity;null==f&&(f=d.Gh);e.kb.Gh=f;e=b.windowOpacityOverride?a.I:a.D;f=b.windowOpacity;null==f&&(f=s5.pk);e.pk=f;e=b.charEdgeStyleOverride?a.I:a.D;f=b.charEdgeStyle;null==f&&(f=d.Sh);e.kb.Sh=f;e=b.fontFamilyOverride?a.I:a.D;f=b.fontFamily;null==f&&(f=d.fontFamily);e.kb.fontFamily=f;a.loaded&&a.lu();c&&t5(a,"display-settings",b)},dya=function(a,b){if(b&&!a.J){var c=A4({ck:0,
lang:"en"});a.J=[c,new x4(c.start,c.end-c.start,0,c.id,g.U("YTP_SAMPLE_SUBTITLES"))];g.VU(a.g,a.J)}else!b&&a.J&&(cya(a,a.J),a.J=null)},cya=function(a,b){g.XU(a.g,b);
(0,g.G)(b,function(a){g.sb(this.M,a)},a);
a.da.Qk()},eya=function(a,b){return a&&g.u(a)&&S4.test(a)?a:b},fya=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},hya=function(a,b){if(a&&g.u(a)){var c=gya.indexOf(a);
return-1!=c?c:b}return b},jya=function(a,b){if(a&&g.u(a)){var c=iya.indexOf(a);
return-1!=c?c:b}return b},kya=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?g.$c(a,-2,4):b},p5=function(a,b){if(!a.ca)return null;
try{var c=a.ca.get(b)}catch(d){a.ca.remove(b)}return c},t5=function(a,b,c){if(a.ca)try{a.ca.set(b,c)}catch(d){}};
g.gI.prototype.Fn=g.ca(4,function(a){return(a=this.Xh(a))?a.o:0});
g.pK.prototype.Fn=g.ca(3,function(){return 0});
g.aI.prototype.J=g.ca(2,function(a){return a?this.toString()==a.toString():!1});
var Vxa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,uxa=/#(.)(.)(.)/,txa=/^#(?:[0-9a-f]{3}){1,2}$/i,S4=/^#(?:[0-9a-f]{3}){1,2}$/i,iya="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" "),gya=["none","raised","depressed","uniform","dropShadow"];var wxa=["left","right","center"];var s5={windowColor:"#080808",pk:0,textAlign:2,Vg:7,ni:50,Mi:100,kb:{background:"#080808",Ve:.75,Sh:0,color:"#fff",fontFamily:4,dj:0,Gh:1,offset:1}};g.p(x4,g.VP);g.p(y4,g.VP);var z4=0;g.p(B4,g.Y);g.h=B4.prototype;g.h.cL=function(a,b){var c=g.Eh(this.element,this.element.parentElement);this.ca=a-c.x;this.da=b-c.y;g.R(this.element,"ytp-dragging")};
g.h.bL=function(a,b){var c=g.Hh(this.element),d=a-this.ca-.02*this.xa,e=b-this.da-.02*this.pa,f=(d+c.width/2)/this.R*3;f=Math.floor(g.$c(f,0,2));var k=(e+c.height/2)/this.ea*3;k=Math.floor(g.$c(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.R;d=100*g.$c(d,0,1);c=(e+k/2*c.height)/this.ea;c=100*g.$c(c,0,1);this.F.params.Vg=l;this.F.params.Mi=c;this.F.params.ni=d;this.o.Vg=l;this.o.Mi=c;this.o.ni=d;this.WB()};
g.h.aL=function(){g.oq(this.element,"ytp-dragging")};
g.h.WB=function(){this.Ji(this.A)};
g.h.Ub=function(){return this.type};
g.h.Ji=function(a){var b=Math.min(this.ox(),this.R),c=this.mx();g.oh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Yp(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.o.ni+2,e=this.o.Vg;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.B.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.o.Mi+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.oh(this.element,a)};
g.h.Yp=function(a){var b;for(b=0;b<a.length&&a[b]==this.A[b];b++);if(this.J||this.A.length>b)b=0,this.J=!1,this.A=[],this.D=[],this.G=[],this.C=null,g.Fd(this.B);for(;b<a.length;b++)xxa(this,a[b])};
g.h.ox=function(){return 0};
g.h.mx=function(){return 0};
g.h.toString=function(){return g.Y.prototype.toString.call(this)};yxa.prototype.B=function(){};E4.prototype.clear=function(){this.B=this.o=this.mode=0;this.g=[];this.reset()};
E4.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var zxa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];F4.prototype.set=function(a){this.g=a};
F4.prototype.get=function(){return this.g};
G4.prototype.clear=function(){this.g=0};
G4.prototype.update=function(){this.g=2==this.g?1:0};
G4.prototype.matches=function(a,b){return 0!=this.g&&a==this.A&&b==this.o};
H4.prototype.cn=function(a){this.qe=a.qe;this.timestamp=a.timestamp;this.g=a.g};
H4.prototype.reset=function(){this.timestamp=this.qe=0;this.g=!1};
I4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.A[b][c];a=0==d.qe?a+"_":a+String.fromCharCode(d.qe)}a+="\n"}return a};
I4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.g=0;this.o=this.Dc=1};
var Exa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Fxa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Gxa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Hxa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];O4.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.o=this.D;this.A=this.F;this.g=this.o;var c=(a<<2)+(b<<1)+0;this.D.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
D4.prototype.reset=function(a){this.C=a;this.g.clear();this.B=this.A;this.A.reset(a,0);this.D.reset(a,1)};Q4.prototype.reset=function(){};g.p(R4,Q4);R4.prototype.g=function(a){var b=[];this.o||(this.o=A4(this.A),b.push(this.o));a=g.ma(a.firstChild.childNodes);for(var c=a.next();!c.done;c=a.next())Nxa(c.value,this.o.id,b);return b};g.p(T4,Q4);
T4.prototype.g=function(a){var b=[];this.o||(this.o=A4(),this.A[this.o.id]=this.o,b.push(this.o));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.A[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=A4());
var k={};f&&(g.Ga(k,f.params),f=f.params.kb)&&(k.kb={},g.Ga(k.kb,f));e.getAttribute("rc")&&(k.So=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.XG=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Vg=0>f||8<f?7:f);e.getAttribute("ah")&&(k.ni=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.Mi=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.ck=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.ck=0));e.getAttribute("bc")&&(k.kb||(k.kb={}),k.kb.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.kb||(k.kb={}),k.kb.Ve=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.kb||(k.kb={}),k.kb.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.uT=(0,window.parseInt)(e.getAttribute("sd"),10));f=(0,window.parseInt)(e.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new y4(c,f,0,e,k)}else c=null}this.A[d]=c;b.push(c);break;case "text":for(d=[],Nxa(a,this.o.id,d),d=g.ma(d),c=d.next();!c.done;c=d.next())c=c.value,this.A[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.p(U4,Q4);
U4.prototype.g=function(a){a.firstChild.getAttribute("format");a=g.ma(a.firstChild.childNodes);for(var b=a.next();!b.done;b=a.next())switch(b=b.value,b.tagName){case "head":var c=b;break;case "body":var d=b}if(c)for(c=g.ma(c.childNodes),a=c.next();!a.done;a=c.next())switch(a=a.value,a.tagName){case "pen":b=a.getAttribute("id");var e=this.o,f={},k=a.getAttribute("p");k&&g.Ga(f,this.o[k]);k=W4(a,"b");null!=k&&(f.bold=k);k=W4(a,"i");null!=k&&(f.Wr=k);k=W4(a,"u");null!=k&&(f.underline=k);k=X4(a,"et");
null!=k&&(f.Sh=k);k=X4(a,"of");null!=k&&(f.offset=k);k=Y4(a,"bc");null!=k&&(f.background=k);k=Y4(a,"ec");null!=k&&(f.jw=k);k=Y4(a,"fc");null!=k&&(f.color=k);k=X4(a,"fs");void 0!=k&&0!=k&&(f.fontFamily=k);k=V4(a,"sz");void 0!=k&&(f.dj=k/100-1);k=V4(a,"bo");void 0!=k&&(f.Ve=k/255);a=V4(a,"fo");void 0!=a&&(f.Gh=a/255);e[b]=f;break;case "ws":b=a.getAttribute("id");this.D[b]=Oxa(this,a);break;case "wp":b=a.getAttribute("id"),this.C[b]=Pxa(this,a)}c=[];if(d)for(a={},b=void 0,d=g.ma(d.childNodes),e=d.next();!e.done;e=
d.next())switch(e=e.value,e.tagName){case "w":var l=Qxa(this,e,!1);(e=a[l.id])&&e.end>l.start&&(e.end=l.start);a[l.id]=l;c.push(l);break;case "p":var m=b,n=Pc;f=[];k=e.getAttribute("w")||this.A;var q=!!W4(e,"a"),r=V4(e,"t")||0,v=V4(e,"d")||5E3;!n&&!q&&m&&m.windowId==k&&m.end>r&&(m.end=r);m=q?6:5;n=this.o[e.getAttribute("p")];for(var B=e.childNodes,E=0;E<B.length;E++){var I=B[E];0<E&&(q=!0);if("s"==I.tagName){var S=I;I=r;var ka=v,Na=k,Ea=q,Fa=m,Ff=S.textContent?S.textContent:"",nb=this.o[S.getAttribute("p")];
S=V4(S,"t")||0;I=new x4(I+S,ka-S,Fa,Na,Ff,Ea,nb)}else I=new x4(r,v,m,k,I.textContent||"",q,n);f.push(I)}b&&"\n"==b.text&&(b.text="");if(0<f.length){b=f[f.length-1];var Pc=null!=e.getAttribute("d");f[0].windowId==this.A&&(l=Qxa(this,e,!0),c.push(l));e=g.ma(f);for(f=e.next();!f.done;f=e.next())f=f.value,f.windowId=l.id,l.o.push(f),c.push(f)}}return c};g.p(Z4,yxa);Z4.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+z4++;c=c/1E3-this.F;d=d/1E3-this.F;a=new y4(c,d-c,5,f,{textAlign:0,Vg:0,ni:2.5*b,Mi:5.33*a});e=new x4(c,d-c,5,f,e);this.A.push(a);this.A.push(e)}};
g.p(a5,Q4);a5.prototype.g=function(a){a=new Z4(a,0,this.A);if(Sxa(a)){for(;a.g<a.o.byteLength;)for(0==a.version&&(a.D=Rxa(a)*(1E3/45)),a.C=$4(a);0<a.C;a.C--){var b=$4(a),c=$4(a),d=$4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.g.push({time:a.D,type:this.track,dw:c,ew:d,order:b.g.length}))}Dxa(this.o,a);return a.A}return[]};
a5.prototype.reset=function(){this.o.clear()};g.p(d5,Q4);
d5.prototype.g=function(a,b){for(var c=[],d=a.split(lya),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!mya.test(f)){var l=u5.exec(f);if(l&&3<=l.length){var m=e5(l[1]);l=e5(l[2])-m;m+=k;f=f.substring(u5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u5.lastIndex=0;var n=f;f={};this.o||(this.o=A4({rs:0}),c.push(this.o));var q=this.o;k=5;if(0>n.indexOf("<")&&0>n.indexOf("&"))c.push(new x4(m,l,k,q.id,n,!1,g.Yb(f)?void 0:f));else{n=n.split(nya);1!=n.length&&(k=6,q="_"+oya++,q=new y4(m,l,k,q,{}),c.push(q));
for(var r=m,v=0;v<n.length;v++){var B=n[v];if(0==v%2){var E=g.Ur("<html>"+B+"</html>");if(E.getElementsByTagName("parsererror").length){var I=E.createElement("span");I.appendChild(E.createTextNode(B))}else I=E.firstChild;Uxa(this,r,l-(r-m),k,q,0<v,I,f,c)}else r=e5(B)}}}u5.lastIndex=0}}return c};
var oya=0,mya=/^NOTE/,lya=/(?:\r\n|\r|\n){2,}/,u5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3}).*(?:\r\n|\r|\n)","gm"),nya=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.p(f5,g.L);f5.prototype.trackCount=function(){return b5(this.o,!0).length};
f5.prototype.Gd=function(){this.g=null};
f5.prototype.W=function(){g.L.prototype.W.call(this);this.Gd()};
f5.prototype.KB=function(){return!1};g.p(g5,f5);g.h=g5.prototype;g.h.hs=function(a,b){var c=this.Ok(a),d=(0,g.z)(function(c){this.A=null;b(c.responseText,a)},this);
this.Gd();this.A=g.LE(c,{format:"RAW",Hb:d,withCredentials:!0})};
g.h.ks=function(a,b,c,d){this.B=c;if(d)for(b=g.ma(d.captionTracks),c=b.next();!c.done;c=b.next())c5(this.o,c.value);a()};
g.h.Ok=function(a){var b=a.I,c={};if(this.B||a.A)c.fmt=this.B||"srv"+a.A;a.g&&(c.tlang=a.g.languageCode);return g.EE(b,c)};
g.h.Gd=function(){f5.prototype.Gd.call(this);this.A&&this.A.abort()};
g.h.W=function(){this.Gd();f5.prototype.W.call(this)};h5.prototype.contains=function(a){a=g.Cb(this.qb,a);return 0<=a||0>a&&1==(-a-1)%2};
h5.prototype.length=function(){return this.qb.length/2};g.p(i5,g.L);g.h=i5.prototype;g.h.W=function(){g.L.prototype.W.call(this);this.o&&this.o.abort()};
g.h.wz=function(a){var b=this.g;this.g=g.db(this.L.ih(a).Ca);b!=this.g&&this.I&&this.I()};
g.h.reset=function(){this.B=new h5;this.o&&(this.o.abort(),this.o=null)};
g.h.Jy=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.si(a);if(a&&!this.o&&!(this.g&&30<this.g.startTime-this.J.getCurrentTime())){a=this.g;a=a.g.ll(a);if(!this.B.contains(a.Ca[0].sa)){var b=g.UJ(g.aK(a,{})),c={format:"RAW",ed:(0,g.z)(this.TQ,this),withCredentials:!0};this.C&&(c.responseType="arraybuffer");this.o=g.LE(b,c);this.A=a;b=this.B;c=this.A.Ca[0].sa;var d=g.Cb(b.qb,c);0<=d||0>d&&1==(-d-1)%2||(d=-d-1,0<d&&1==c-b.qb[d-1]&&d<b.qb.length&&1==b.qb[d]-c?(g.rb(b.qb,d),g.rb(b.qb,d-1)):0<d&&1==
c-b.qb[d-1]?b.qb[d-1]=c:d<b.qb.length&&1==b.qb[d]-c?b.qb[d]=c:(g.yb(b.qb,d,0,c),g.yb(b.qb,d+1,0,c)))}this.g=g.db(a.Ca)}this.F.start()};
g.h.TQ=function(a){(this.C?!a.response:!a.responseText)||400<=a.status||null===this.D||(this.C?this.D(a.response,1E3*this.A.Ca[0].startTime):this.D(a.responseText,1E3*this.A.Ca[0].startTime));this.o=this.A=null};g.p(j5,f5);g.h=j5.prototype;g.h.hs=function(a,b){this.Gd();var c=Yxa(this,a.o);if(c){var d=1E3*c.index.Fn(c.index.ug()),e=g.X(this.C).se;this.A=new i5(new g.IJ,this.C,c,function(c,e){b(c,a,e,d)},e,(0,g.z)(function(){e&&(this.A&&this.A.reset(),this.g&&this.g.reset(),this.D=!0)},this))}};
g.h.KB=function(){var a=this.D;this.D=!1;return a};
g.h.ks=function(a){g.X(this.C).se?(c5(this.o,new g.aI({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),c5(this.o,new g.aI({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}))):c5(this.o,new g.aI({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()};
g.h.Gd=function(){f5.prototype.Gd.call(this);this.A&&(this.A.dispose(),this.A=null)};
g.h.Ok=function(){return""};
g.h.W=function(){this.Gd();f5.prototype.W.call(this)};g.p(k5,B4);k5.prototype.Yp=function(a){var b=this.F.o;B4.prototype.Yp.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Ga(d,c.o);g.Ga(d,pya);var e=c.o;var f=d}xxa(this,c,d)}};
var pya={qr:!0};g.p(l5,B4);g.h=l5.prototype;g.h.WB=function(){g.Zt(this.X)};
g.h.XQ=function(){g.oq(this.element,"ytp-rollup-mode");this.Ji(this.la,!0)};
g.h.ox=function(){return this.I};
g.h.mx=function(){return this.F.params.So*m5(this)};
g.h.Ji=function(a,b){this.la=a;if(m5(this)){for(var c=0,d=0;d<this.A.length&&c<a.length;d++)this.A[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.A.concat(a.slice(c)));c=this.I;this.I=0;B4.prototype.Ji.call(this,a);this.I=Math.max(c,this.B.offsetWidth+1);c=this.F.params.So*m5(this)-this.B.offsetHeight;c!=this.O&&(b||(0,window.isNaN)(this.O)||(g.R(this.element,"ytp-rollup-mode"),g.Yt(this.X)),g.oh(this.B,"transform",c?"translateY("+c+"px)":""),this.O=c);B4.prototype.Ji.call(this,a)}else B4.prototype.Ji.call(this,
a)};g.p(n5,f5);g.h=n5.prototype;g.h.hs=function(a,b){var c=this.Ok(a),d=(0,g.z)(function(c){this.A=null;b(c.responseText,a)},this);
this.Gd();this.A=g.LE(c,{format:"RAW",Hb:d,withCredentials:!0})};
g.h.ks=function(a,b,c){var d=this.C;b={type:"list",tlangs:1,v:this.B,fmts:Number(b||!1),vssids:1};this.vy&&(b.asrs=1);d=g.EE(d,b);b=(0,g.z)(function(b){this.A=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.o,e=g.ma(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),v=m.getAttribute("kind"),B=m.getAttribute("id"),E="true"==m.getAttribute("cantran");
m=m.getAttribute("vss_id");c5(d,new g.aI({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:v,id:B,is_servable:!0,is_translateable:E,vss_id:m}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),l={languageCode:l,languageName:n,languageOriginal:q,id:r},this.D[l.languageCode]=l.languageName,this.F.push(new g.$H(l))}a()},this);
this.Gd();this.A=g.LE(d,{format:"RAW",Hb:b,withCredentials:!0})};
g.h.Ok=function(a){var b=this.C,c={v:this.B,type:"track",lang:a.o,name:a.C,kind:a.B,fmt:a.A};a.g&&(c.tlang=v4(a));return b=g.EE(b,c)};
g.h.Gd=function(){f5.prototype.Gd.call(this);this.A&&this.A.abort()};
g.h.W=function(){this.Gd();f5.prototype.W.call(this)};g.p(q5,g.EV);g.h=q5.prototype;g.h.W=function(){if(this.G){var a=this.L.app.C;a&&qxa(a)}else dya(this,!1);g.EV.prototype.W.call(this)};
g.h.lz=function(){return this.G?!this.A.wa:this.A.captionTracks.length&&this.g.xh().Hk?!0:Zxa(this)};
g.h.load=function(a){g.EV.prototype.load.call(this);this.F=this.g.xh();if(this.C||a)this.o?(this.G&&!this.B.experiments.g("disable_native_caption_api")?aya(this,!0):a?this.tB(a,this.o):3!=this.g.Qa()&&this.C.hs(this.o,(0,g.z)(this.tB,this)),this.g.ua("captionschanged",u4(this.o))):this.g.ua("onCaptionsTrackListChanged");else{var b;a=this.A;a.wa||g.X(this.L).se&&null!=a.oa&&null!=a.oa.g.rawcc?b=new j5(this.A.oa,this.g):this.A.captionTracks.length?b=new g5(this.A):b=new n5(this.A.Rm,this.A.videoId,
this.A.Yg||this.B.Yg||g.WN(this.A,"yt:cc_default_lang")||this.B.Oa,this.A.Qm);this.C=b;b.ks((0,g.z)(this.yR,this),!0,this.G?"vtt":void 0,this.g.xh())}};
g.h.unload=function(){this.G?this.B.experiments.g("disable_native_caption_api")?qxa(this.L.app.C):this.o&&aya(this,!1):(this.ea&&g.$t(this.ea),g.YU(this.g,"captions"),this.M=[],this.C&&this.C.Gd(),this.J&&g.VU(this.g,this.J),this.lu());g.EV.prototype.unload.call(this);var a=g.HU(this.g.app);a&&a.D&&g.kP(a.D.A);this.g.ua("captionschanged",{})};
g.h.yR=function(){if(this.Y||Zxa(this))var a=$xa(this,this.Y);if(this.G){for(var b=b5(this.C.o,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.bI(e),srclang:v4(e),src:this.C.Ok(e),id:e.toString()};e==a&&(f["default"]=1);c.push(g.K("TRACK",f))}a=this.L.app.C;for(b=0;b<c.length;b++)a.g.appendChild(c[b]);(c=this.L.app.C.g)&&c.textTracks&&c.textTracks.addEventListener&&!this.B.experiments.g("disable_native_caption_api")&&this.R.P(c.textTracks,"change",this.zR)}else!this.o&&a&&r5(this,
a),this.g.ua("onCaptionsTrackListChanged"),this.g.ua("onApiChange")};
g.h.zR=function(){for(var a=this.L.app.C.g.textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=b5(this.C.o,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.o:null)!=b&&r5(this,b,!0)};
g.h.AT=function(){this.B.experiments.g("disable_native_caption_api")?this.loaded&&!this.G&&this.unload():!this.o&&this.G||this.unload()};
g.h.tB=function(a,b,c,d){if(a){this.C.KB()&&(this.M=[],g.YU(this.L,"captions"),this.da.Qk());a=Xxa(this.C,a,b,c,d);c={trackName:b.C,trackKind:b.B,trackLangCode:v4(b)};b.g&&(c.fromLangCode=b.o);g.QU(this.g,"cc",c);if(this.o!=(this.F&&this.F.Hk)){if(this.Y&&!g.XL(this.B)&&!g.mM(this.B)){g.$t(this.ea);b=A4({Vg:0,ni:5,Mi:5,So:2,textAlign:0,ck:0,lang:"en"});this.X=[b];c=g.U("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON");this.ga||(d=new g.jV(g.kE()),g.M(this,d),this.ga=d.element);d=b.end-b.start;var e=g.bI(this.o);
e&&this.X.push(new x4(b.start,d,0,b.id,e));this.X.push(new x4(b.start,d,0,b.id,c[0]),new x4(b.start,d,0,b.id,this.ga,!0),new x4(b.start,d,0,b.id,c[1],!0));g.VU(this.g,this.X);g.Yt(this.ea)}if(this.Y||g.XL(this.B))t5(this,"module-enabled",!0),this.F&&(this.F.g=this.o);(b=g.HU(this.g.app))&&b.D&&g.kP(b.D.A)}g.VU(this.g,a);this.Y=!1}};
g.h.IK=function(a){this.M.push(a);this.da.Qk()};
g.h.JK=function(a){g.sb(this.M,a);this.da.Qk()};
g.h.tS=function(a){if(a instanceof y4){var b=this.O[a.id];b&&b.F!=a&&(b.dispose(),delete this.O[a.id],b=null);b||(b=bya(this,a))&&(this.O[a.id]=b)}else b=a.windowId,this.aa[b]||(this.aa[b]=[]),this.aa[b].push(a)};
g.h.LS=function(){cya(this,this.X);this.X=null};
g.h.ZC=function(){this.da.stop();rxa(this.aa);this.M.sort(g.XP);var a=this.M;if(this.J){var b=(0,g.Jd)(a,function(a){return-1==this.J.indexOf(a)},this);
b.length&&(a=b)}(0,g.G)(a,this.tS,this);g.Lb(this.O,function(a,b){this.aa[b]?(a.element.parentNode||g.bV(this.g,a.element,4),a.Ji(this.aa[b])):(a.dispose(),delete this.O[b])},this)};
g.h.VB=function(){o5(this,{},!0)};
g.h.Qq=function(){var a=s5.kb;a={background:a.background,backgroundOpacity:a.Ve,charEdgeStyle:a.Sh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.dj,textOpacity:a.Gh,windowColor:s5.windowColor,windowOpacity:s5.pk};var b=p5(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.ou=function(a,b){var c={};g.Ga(c,p5(this,"display-settings"));g.Ga(c,a);o5(this,c,b);this.g.T("captionssettingschanged")};
g.h.lu=function(){!this.G&&this.loaded&&(g.Lb(this.O,function(a,b){a.dispose();delete this.O[b]},this),this.ZC())};
g.h.Cs=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.$c(b,-2,4);this.ou({fontSizeIncrement:c});return c;case "reload":b&&!this.G&&r5(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.B.Fb&&t5(this,"module-enabled",!!b);break;case "track":if(!this.C)return{};if(b){if(this.G)break;if(!g.Aa(b))break;if(g.Yb(b)){r5(this,null,!0);break}for(var d=b5(this.C.o,!0),e=0;e<d.length;e++){var f=d[e];f.o!=b.languageCode||c&&f.D!=b.languageName||(c=b.translationLanguage?pxa(f,
b.translationLanguage):f)}!c||c==this.o&&this.loaded||r5(this,c,!0)}else return this.loaded&&this.o&&this.o!=(this.F&&this.F.Hk)?u4(this.o):{};return"";case "tracklist":return this.C?(0,g.H)(b5(this.C.o,b&&b.includeAsr),function(a){return u4(a)}):[];
case "translationLanguages":return this.C?this.C.F:[];case "displaySettings":c=this.Qq();if(g.XL(this.B)&&b&&g.Aa(b))if(b.reset)this.VB();else{f={};for(d in b)switch(d){case "color":case "background":case "windowColor":f[d]=eya(b[d],c[d]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[d]=fya(b[d],c[d]);break;case "charEdgeStyle":f[d]=hya(b[d],c[d]);break;case "fontSizeIncrement":f[d]=kya(b[d],c[d]);break;case "fontFamilyOption":f.fontFamily=jya(b[d],c[d])}for(e in f)f[e+
"Override"]=!0;this.ou(f,!0);c=this.Qq()}c.fontFamilyOption=iya[c.fontFamily];c.charEdgeStyle=gya[c.charEdgeStyle];return c;case "sampleSubtitles":this.G||void 0==b||dya(this,!!b);break;case "xmlTrack":b&&this.B.Fb&&(this.G||r5(this,new g.aI({languageName:b.name}),!1,b.xml))}};
g.h.GK=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.B.Fb&&a.push("stickyLoading","xmlTrack");return a};
g.h.HK=function(){var a=this.o;return a?{cc:a.F}:{}};
g.h.MC=function(){this.loaded&&this.o?(t5(this,"module-enabled",!1),this.unload()):r5(this,this.o||$xa(this,!0),!0)};
g.h.eO=function(){this.A.captionTracks.length&&(this.loaded&&this.unload(),this.lz()&&this.load())};g.hY.captions=q5;})(_yt_player);
